services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring-boot-sample
      MYSQL_USER: spring-boot
      MYSQL_PASSWORD: zaq12wsx
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.db-data/data:/var/lib/mysql
      - ./.db-data/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.db-data/sql:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 23306:3306
